deploymentMode: SingleBinary
loki:
  ingester:
    chunk_idle_period: 10s
    chunk_retain_period: 20s
    max_chunk_age: 30s
    flush_check_period: 10s
  commonConfig:
    replication_factor: 1
  schemaConfig:
      configs:
        - from: 2025-04-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h
  auth_enabled: false
  storage:
    bucketNames:
      chunks: loki-data
      ruler: loki-data
      admin: loki-data
    type: s3
    s3:
      endpoint: "http://bitnami-minio.default.svc.cluster.local:9000"
      s3ForcePathStyle: true
      accessKeyId: "admin123"
      secretAccessKey: "12345678"
      insecure: true
chunksCache:
  enabled: false
resultsCache:
  enabled: false