---
- import_playbook: mysql.yaml

- hosts: native

  pre_tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
      become: yes

  tasks:
    - name: "Clone the Spring repository"
      git:
        repo: "https://github.com/GianniCapocci/DevOps.git"
        dest: "{{ appdir }}"
        version: "{{ branch }}"
        force: yes

    - name: "Populate application.properties"
      lineinfile:
        dest: "{{ appdir }}/src/main/resources/application.properties"
        state: present
        regexp: "^{{item.key}}="
        line: "{{item.key}}={{item.value}}"
      with_items:
        - "{{app.env | dict2items}}"

    - name: "Download java agent jar file"
      ansible.builtin.get_url:
        url: https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.14.0/opentelemetry-javaagent.jar
        dest: "{{ appdir }}"

    - name: Copy config file for otel agent
      ansible.builtin.copy:
        src: /home/vagrant/ansible/files/agent-config-native.properties
        dest: "{{ appdir }}/agent-config-native.properties"

    - name: "Build the Spring application"
      command: "./mvnw package -Dmaven.test.skip "
      args:
        chdir: "{{ appdir }}"

    - name: copy spring service file
      template:
        src: ../files/spring.service.j2
        dest: "/etc/systemd/system/spring.service"
      become: yes
      become_user: root
      notify: restart spring

    - name: reload spring service
      service:
        name: spring
        state: restarted
      become: yes

    - name: ensure spring service started
      service:
        name: spring
        state: started
        enabled: yes
      become: yes

    - name: "APT - install nginx"
      apt:
        name: nginx
        update_cache: yes
      become: yes

    - name: copy nginx conf file
      template:
        src: ../files/nginx.http.j2
        dest: "/etc/nginx/sites-available/spring"
      become: yes

    - name: enable spring site in nginx
      file:
        src: "/etc/nginx/sites-available/spring"
        dest: "/etc/nginx/sites-enabled/spring"
        state: link
      become: yes
      notify: restart nginx

    - name: de-activate default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes
      notify: restart nginx

  handlers:
  - name: restart spring
    service:
      name: spring
      state: restarted
    become: yes

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: yes
